# Generated by Django 5.2 on 2025-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification_level',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'MBBS - Bachelor of Medicine, Bachelor of Surgery'), (2, 'BDS - Bachelor of Dental Surgery'), (3, 'BHMS - Bachelor of Homeopathic Medicine & Surgery'), (4, 'BAMS - Bachelor of Ayurvedic Medicine & Surgery'), (5, 'BUMS - Bachelor of Unani Medicine & Surgery'), (6, 'BSMS - Bachelor of Siddha Medicine & Surgery'), (7, 'BNYS - Bachelor of Naturopathy and Yogic Sciences'), (8, 'B.Sc Nursing'), (9, 'GNM - General Nursing and Midwifery'), (10, 'BPT - Bachelor of Physiotherapy'), (11, 'BOT - Bachelor of Occupational Therapy'), (12, 'BMLT - Bachelor of Medical Laboratory Technology'), (13, 'B.Pharm - Bachelor of Pharmacy'), (14, 'MD - Doctor of Medicine'), (15, 'MS - Master of Surgery'), (16, 'MPT - Master of Physiotherapy'), (17, 'MOT - Master of Occupational Therapy'), (18, 'MMLT - Master of Medical Lab Technology'), (19, 'MPH - Master of Public Health'), (20, 'MPTh - Master of Physiotherapy'), (21, 'MHA - Master of Hospital Administration'), (22, 'M.Sc Nursing'), (23, 'DM - Doctorate of Medicine (Super-specialty)'), (24, 'MCh - Magister Chirurgiae / Master of Surgery (Super-specialty)'), (25, 'M.Pharm - Master of Pharmacy'), (26, 'Pharm.D - Doctor of Pharmacy'), (27, 'PhD - Doctor of Philosophy'), (28, 'M.Phil - Master of Philosophy'), (29, 'DNB - Diplomate of National Board'), (30, 'Postgraduate Diploma (Various Specializations)'), (31, 'Diploma in Paramedical Sciences'), (32, 'DMLT - Diploma in Medical Lab Technology'), (33, 'MD (USA)'), (34, 'DO - Doctor of Osteopathic Medicine (USA)'), (35, 'MBChB - Bachelor of Medicine and Bachelor of Surgery (UK)'), (36, 'MBBCh - Bachelor of Medicine and Bachelor of Surgery (Ireland/South Africa)')], help_text='Choose your qualification by selecting', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'General Medicine'), (2, 'Family Medicine'), (3, 'Internal Medicine'), (4, 'Pediatrics'), (5, 'Obstetrics and Gynecology'), (6, 'General Surgery'), (7, 'Orthopedics'), (8, 'Cardiology'), (9, 'Neurology'), (10, 'Neurosurgery'), (11, 'Gastroenterology'), (12, 'Hepatology'), (13, 'Endocrinology'), (14, 'Pulmonology (Chest Medicine)'), (15, 'Nephrology'), (16, 'Urology'), (17, 'Dermatology'), (18, 'Ophthalmology'), (19, 'ENT (Otorhinolaryngology)'), (20, 'Psychiatry'), (21, 'Radiology'), (22, 'Oncology'), (23, 'Hematology'), (24, 'Rheumatology'), (25, 'Anesthesiology'), (26, 'Emergency Medicine'), (27, 'Critical Care Medicine'), (28, 'Nuclear Medicine'), (29, 'Geriatrics'), (30, 'Allergy and Immunology'), (31, 'Infectious Diseases'), (32, 'Plastic Surgery'), (33, 'Pediatric Surgery'), (34, 'Thoracic Surgery'), (35, 'Vascular Surgery'), (36, 'Pain Management'), (37, 'Sports Medicine'), (38, 'Rehabilitation Medicine (PM&R)'), (39, 'Occupational Medicine'), (40, 'Transfusion Medicine'), (41, 'Pathology'), (42, 'Medical Genetics'), (43, 'Forensic Medicine'), (44, 'Sexual Health and Andrology'), (45, 'Sleep Medicine'), (46, 'Preventive and Social Medicine (PSM)')], help_text='Choose your specialization by selecting', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Nurse'), (4, 'Staff'), (5, 'Admin')], default=1),
        ),
    ]
