# Generated by Django 5.2 on 2025-05-10 18:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_blood_group_customuser_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], help_text='Select the days you are available.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clinic_location',
            field=models.CharField(blank=True, help_text='If you have your own clinic, please enter the location here.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
