# Generated by Django 5.2 on 2025-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_is_staff_customuser_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official license or registration number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Nurse')], default=1),
        ),
    ]
