# Generated by Django 5.2 on 2025-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official license number or registration number', max_length=50, null=True),
        ),
    ]
