# Generated by Django 5.2 on 2025-05-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_qualification_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualification_level',
            field=models.ForeignKey(blank=True, help_text='Choose your qualification by selecting', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.qualification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.ForeignKey(blank=True, help_text='Choose your specialization by selecting', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.specialization'),
        ),
    ]
