# Generated by Django 5.2 on 2025-05-11 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_qualification_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialization_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
