# Generated by Django 5.2 on 2025-05-12 18:55

from django.db import migrations, models
import uuid

def generate_unique_registration_codes(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    for user in CustomUser.objects.filter(registration_code__isnull=True):
        # Generate a unique 16-character code using UUID
        code = uuid.uuid4().hex[:16]
        # Ensure it's unique
        while CustomUser.objects.filter(registration_code=code).exists():
            code = uuid.uuid4().hex[:16]
        user.registration_code = code
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_registration_code_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_unique_registration_codes),
        migrations.AlterField(
            model_name='customuser',
            name='registration_code',
            field=models.CharField(default=2, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
