# Generated by Django 5.2 on 2025-05-12 18:57

from django.db import migrations, models
import uuid


def generate_unique_registration_no(apps, schema_editor):
    CustomUser = apps.get_model('core', 'CustomUser')
    for user in CustomUser.objects.filter(registration_number__isnull=True):
        code = uuid.uuid4().hex[:16]
        while CustomUser.objects.filter(registration_number=code).exists():
            code = uuid.uuid4().hex[:16]
        user.registration_number = code
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_registration_code'),
    ]

    operations = [
        migrations.RunPython(generate_unique_registration_no),
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(
                help_text='Official license number or registration number',
                max_length=50,
                unique=True
            ),
        ),
    ]

