# Generated by Django 5.2 on 2025-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customuser_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Select Role'), (1, 'Patient'), (2, 'Doctor'), (3, 'Nurse')], default=0),
        ),
    ]
