# Generated by Django 5.2 on 2025-05-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('html_header', models.TextField(blank=True, null=True)),
                ('html_footer', models.TextField(blank=True, null=True)),
                ('heading', models.CharField(max_length=100)),
                ('plain_text', models.TextField()),
                ('html', models.TextField()),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ('template_name', 'locale'),
                'permissions': (('mandate_add_emailtemplate', 'Mandate Add EmailTemplate'), ('mandate_edit_emailtemplate', 'Mandate Edit EmailTemplate'), ('mandate_delete_emailtemplate', 'Mandate Delete EmailTemplate')),
            },
        ),
        migrations.CreateModel(
            name='PasswordGenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hash', models.CharField(max_length=64)),
                ('expired', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=64, unique=True)),
                ('expired', models.BooleanField(default=False)),
                ('expiry_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
