# Generated by Django 5.2 on 2025-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailtemplate_passwordgenlink_registrationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official license number or registration number', max_length=50, null=True, unique=True),
        ),
    ]
