# Generated by Django 5.2 on 2025-06-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customuser_registration_number'),
        ('hospital_app', '0013_appointment_doctor_delete_doctorhospitalassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospitalservices'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital'),
        ),
    ]
