# Generated by Django 5.2 on 2025-05-10 16:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
