# Generated by Django 5.2 on 2025-05-10 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='closed_on',
            field=models.DateField(blank=True, help_text='The date when the hospital was opened', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hp_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_expires_on',
            field=models.DateField(blank=True, help_text='Date when the hospital license expires', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_issued_on',
            field=models.DateField(blank=True, help_text='Date when the hospital license was issued', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_number',
            field=models.CharField(blank=True, help_text='License number of the hospital', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', help_text="The current status of the hospital's license", max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='opened_on',
            field=models.DateField(default='2023-01-01', help_text='The date when the hospital was opened'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DoctorHospitalAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(help_text='Date the doctor joined the hospital')),
                ('role', models.CharField(choices=[('Consultant', 'Consultant'), ('Specialist', 'Specialist'), ('Resident', 'Resident'), ('Visiting', 'Visiting')], help_text="Doctor's role in the hospital", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the doctor is currently active in the hospital')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_association_with', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_association_with', to='hospital_app.hospital')),
            ],
            options={
                'unique_together': {('doctor', 'hospital')},
            },
        ),
    ]
