# Generated by Django 5.2 on 2025-05-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_hospital_closed_on_hospital_hp_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Start time of the time slot (e.g., 08:00 AM)')),
                ('end_time', models.TimeField(help_text='End time of the time slot (e.g., 10:00 AM)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(help_text='Date of the appointment'),
        ),
        migrations.CreateModel(
            name='HospitalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service offered by the hospital', max_length=100)),
                ('service_description', models.TextField(help_text='Description of the service offered by the hospital')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='Price of the service offered by the hospital', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_offered', to='hospital_app.hospital')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL)),
                ('timslot', models.ManyToManyField(blank=True, help_text='Time slots available for the service', to='hospital_app.timeslot')),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_services', to='hospital_app.hospitalservices'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_timeslot', to='hospital_app.timeslot'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
