# Generated by Django 5.2 on 2025-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_timeslot_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalservices',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service offered by the hospital', max_digits=10, null=True),
        ),
    ]
