# Generated by Django 5.2 on 2025-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_alter_hospitalservices_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
