# Generated by Django 5.2 on 2025-05-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_appointment_appointment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_code',
        ),
    ]
