# Generated by Django 5.2 on 2025-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_remove_appointment_appointment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_rejection',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Cancelled'), (4, 'Completed'), (5, 'Reject')], default=1),
        ),
    ]
