# Generated by Django 5.2 on 2025-06-06 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0012_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_for_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DoctorHospitalAssociation',
        ),
    ]
